#!/usr/bin/env python3
"""
Plot and compare HRTF magnitude responses across multiple SOFA files.

Reads impulse-response WAVs generated by run_sofalizer_diagnostics.ps1 and produces:
  hrtf_spectrum_<label>.png  — 4-angle grid for each SOFA file
  hrtf_spectrum_compare.png  — single-angle (0° and 90°) overlay of all SOFA files
"""

import sys
import os
import numpy as np
import scipy.io.wavfile as wav
import matplotlib
matplotlib.use("Agg")  # headless — no display required
import matplotlib.pyplot as plt

BASE   = "S:/code/mumble"
ANGLES = [0, 90, 180, 270]
LABELS = ["current", "cipic_124", "sadie_d1", "sadie_h12"]
COLORS = ["tab:blue", "tab:orange", "tab:green", "tab:red"]


def read_hrtf_wav(label: str, angle: int):
    path = os.path.join(BASE, f"hrtf_{label}_{angle}deg.wav")
    try:
        sr, data = wav.read(path)
    except FileNotFoundError:
        return None, None, None
    scale = np.iinfo(data.dtype).max if data.dtype.kind == "i" else 1.0
    data  = data.astype(float) / scale
    return sr, data, path


def magnitude_db(signal):
    return 20 * np.log10(np.abs(np.fft.rfft(signal)) + 1e-12)


# ── Per-SOFA 4-angle grid ────────────────────────────────────────────────────
for label in LABELS:
    fig, axes = plt.subplots(2, 2, figsize=(12, 8), sharex=True, sharey=True)
    fig.suptitle(f"HRTF Magnitude Response — {label}\n(blue=L, orange=R)")

    for ax, angle in zip(axes.flat, ANGLES):
        sr, data, path = read_hrtf_wav(label, angle)
        if data is None:
            ax.set_title(f"{angle}° — file not found")
            continue

        freqs = np.fft.rfftfreq(data.shape[0], d=1.0 / sr)
        for ch, ch_label, color in [(0, "L", "tab:blue"), (1, "R", "tab:orange")]:
            ax.plot(freqs, magnitude_db(data[:, ch]),
                    label=ch_label, color=color, linewidth=0.8)

        ax.set_title(f"Azimuth {angle}°")
        ax.set_xlabel("Frequency (Hz)")
        ax.set_ylabel("Magnitude (dB)")
        ax.set_xlim(100, sr // 2)
        ax.set_xscale("log")
        ax.set_ylim(-80, 20)
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)

    plt.tight_layout()
    out = os.path.join(BASE, f"hrtf_spectrum_{label}.png")
    plt.savefig(out, dpi=150)
    plt.close()
    print(f"Saved: {out}")


# ── Cross-SOFA comparison: L channel at 0° and 90° ──────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)
fig.suptitle("HRTF Comparison — L channel  (left: 0° front, right: 90° left-side)")

for ax, angle in zip(axes, [0, 90]):
    for label, color in zip(LABELS, COLORS):
        sr, data, _ = read_hrtf_wav(label, angle)
        if data is None:
            continue
        freqs = np.fft.rfftfreq(data.shape[0], d=1.0 / sr)
        ax.plot(freqs, magnitude_db(data[:, 0]),
                label=label, color=color, linewidth=1.0)

    ax.set_title(f"Azimuth {angle}°")
    ax.set_xlabel("Frequency (Hz)")
    ax.set_ylabel("Magnitude (dB)")
    ax.set_xlim(100, 22050)
    ax.set_xscale("log")
    ax.set_ylim(-60, 20)
    ax.legend()
    ax.grid(True, alpha=0.3)

plt.tight_layout()
out = os.path.join(BASE, "hrtf_spectrum_compare.png")
plt.savefig(out, dpi=150)
plt.close()
print(f"Saved: {out}")
